version: '3.6'

services:
  spring-web:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8081
    depends_on:
      - maria-db

  maria-db:
    container_name: maria-db
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - ./db/:/var/lib/mysql/
    ports:
      - 3366:3306
    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'
      
  
